#!/usr/bin/env bash
#
# tcpaccept Trace TCP accept()s.
#
# USAGE: tcpaccept [-h] [-t] [-p PID]
#
# This uses dynamic tracing of the kernel inet_csk_accept() socket function,
# and will need to be modified to match kernel changes.
#
# 25-Sep-2018   Ethercflow   Created this.

### default variables
tracing=/sys/kernel/debug/tracing
flock=/var/tmp/.ftrace-lock
bufsize_kb=4096
start_ts=0; opt_duration=0; duration=; opt_timestamp=0;
trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section

function usage {
    cat <<-END >&2
    USAGE: tcpaccept [-ht]
                      -h       # help message
                      -t       # include timestamp on output
    eg,
         ./tcpaccept           # trace all TCP connect()s
         ./tcpaccpet  -t       # include timestamps
END
   exit
}

function warn {
    if ! eval "$@"; then
        echo >&2 "WARNING: command failed \"$@\""
    fi
}

function end {
    echo 2>/dev/null
    echo "Ending tracing..." 2>/dev/null
    cd $tracing
    warn "echo 0 > events/tcp/inet_csk_accept_return/enable"
    warn "echo > trace"
    (( wroteflock )) && warn "rm $flock"
}

function die {
    echo >&2 "$@"
    exit 1
}

function edie {
    # die with a quiet end()
    echo >&2 "$@"
    exec >/dev/null 2>&1
    end
    exit 1
}

### process options
while getopts ht opt
do
    case $opt in
    t) opt_timestamp=1 ;;
    h|?) usage ;;
    esac
done
shift $(( $OPTIND - 1 ))
if (( $# )); then
    opt_duration=1
    duration=$1
    shift
fi

### option logic
if (( opt_duration )); then
    echo "Tracing tcpaccept for $duration seconds (buffered)..."
else
    echo "Tracing tcpaccept ... Hit Ctrl-C to end"
fi

# select awk
(( opt_duration )) && use=mawk || use=gawk	# workaround for mawk fflush()
[[ -x /usr/bin/$use ]] && awk=$use || awk=awk
wroteflock=1

### check permissions
cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
    debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"

### ftrace lock
[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
echo $$ > $flock || die "ERROR: unable to write $flock."

### setup and begin tracing
echo nop > current_tracer
warn "echo $bufsize_kb > buffer_size_kb"
if ! echo 1 > events/tcp/inet_csk_accept_return/enable; then
    edie "ERROR: enabling . Exiting."
fi

(( opt_timestamp )) && printf "%-12s " "TIME(s)"
printf "%-8s " "PID"
printf "%-12s " "COMM"
printf "%-20s " "RADDR"
printf "%-6s " "RPORT"
printf "%-20s " "SADDR"
printf "%-6s\n" "SPORT"

#
# Determine output format. It may be one of the following (newest first):
#           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
#           TASK-PID    CPU#    TIMESTAMP  FUNCTION
# To differentiate between them, the number of header fields is counted,
# and an offset set, to skip the extra column when needed.
#
offset=$($awk 'BEGIN { o = 0; }
    $1 == "#" && $2 ~ /TASK/ && NF == 6 { o = 1; }
    $2 ~ /TASK/ { print o; exit }' trace)

### print trace buffer
warn "echo > trace"
( if (( opt_duration )); then
    # wait then dump buffer
    sleep $duration
    cat trace
else
    # print buffer live
    cat trace_pipe
fi ) | $awk -v o=$offset -v start_ts=$start_ts -v opt_timestamp=$opt_timestamp '
    # common fields
    $1 != "#" {
        # task name can contain dashes
        comm = pid = $1
        sub(/-[0-9][0-9]*/, "", comm)
        sub(/.*-/, "", pid)
        time = $(3+o); sub(":", "", time)
    }

    # inet_csk_accept_return
    $1 != "#" && $0 ~ /inet_csk_accept_return/ {
        saddr = $(7+o); sub(/.*=/, "", saddr)
        sport = $(5+o); sub(/.*=/, "", sport)
        raddr = $(8+o); sub(/.*=/, "", raddr)
        rport = $(6+o); sub(/.*=/, "", rport)

        if (opt_timestamp) {
            if (start_ts == 0) 
                start_ts = time
            lasted_s = time - start_ts
            printf "%-12.6f ", lasted_s
        }

        printf "%-8s %-12s ", pid, comm
        printf "%-20s ", raddr
        printf "%-6s ", rport
        printf "%-20s ", saddr
        printf "%-6s\n", sport

	if (!opt_duration)
	    fflush()

        next
    }

    $0 ~ /LOST.*EVENTS/ { print "WARNING: " $0 > "/dev/stderr" }
'

### end tracing
end
